repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Check for numpy imports
        entry: git grep -l "import numpy"
        language: system
        types: [python]
        exclude: |
          (?x)^(
            \.pre-commit-config\.yaml|
            omnigibson/utils/deprecated_utils\.py| # Keep Numpy import for deprecated Omniverse utils
            omnigibson/utils/numpy_utils\.py|      # Utilities specifically for numpy operations and dtype
            tests/test_transform_utils\.py         # This test file uses Scipy and Numpy
          )$
        stages: [commit]