# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# The above line is included to enable intellisense for mkdocs.yml file in VSCode. It is not a valid
# part of the mkdocs.yml file and should remain commented out.

site_name: OmniGibson Documentation
repo_name: StanfordVL/OmniGibson
site_url: https://behavior.stanford.edu/omnigibson
repo_url: https://github.com/StanfordVL/OmniGibson
theme: 
  name: material
  logo: assets/OmniGibson_logo.png
  favicon: assets/OmniGibson_logo.png
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.code.copy

  extra:
    homepage: https://behavior.stanford.edu

  custom_dir: .overrides

  # color info
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/fold_api_reference.js

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: omnigibson
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

# extra plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [omnigibson]
          options:
            docstring_options:
              returns_named_value: false
  # - social
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - offline

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Quickstart: getting_started/quickstart.md
    - Important Concepts: getting_started/important_concepts.md
    - Examples: getting_started/examples.md
  - OmniGibson Modules:
    - Overview: modules/overview.md
    - Prims: modules/prims.md
    - Objects: modules/objects.md
    - Object States: modules/object_states.md
    - Robots: modules/robots.md
    - Controllers: modules/controllers.md
    - Sensors: modules/sensors.md
    - Systems: modules/systems.md
    - Scenes: modules/scenes.md
    - Transition Rules: modules/transition_rules.md
    - Simulator: modules/simulator.md
    - Tasks: modules/tasks.md
    - Environments: modules/environments.md
    - Vector Environments: modules/vector_environments.md
    - Setting Macros: modules/setting_macros.md
    - Under the Hood - Isaac Sim: modules/under_the_hood.md
  - BEHAVIOR Components:
    - BEHAVIOR Tasks: behavior_components/behavior_tasks.md
    - BEHAVIOR Knowledgebase: behavior_components/behavior_knowledgebase.md
  - Tutorials:
    - Demo Collection: tutorials/demo_collection.md
    - Running on a Compute Cluster: tutorials/running_on_a_compute_cluster.md
    - Remote Streaming: tutorials/remote_streaming.md    
    - Saving and Loading Simulation State: tutorials/save_load.md
    - Customizing Robots: tutorials/customizing_robots.md
    - Custom Robot Import: tutorials/custom_robot_import.md
  - Miscellaneous:
    - Roadmap: miscellaneous/roadmap.md
    - Speed Optimization: miscellaneous/speed_optimization.md
    - FAQ: miscellaneous/faq.md
    - Known Issues & Troubleshooting: miscellaneous/known_issues.md
    - Contributing: miscellaneous/contributing.md
    - Contact Us: miscellaneous/contact.md
  - API Reference: reference/*
  - Changelog: https://github.com/StanfordVL/OmniGibson/releases

extra:
  analytics:
    provider: google
    property: G-6L1G6GMR63