# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# The above line is included to enable intellisense for mkdocs.yml file in VSCode. It is not a valid
# part of the mkdocs.yml file and should remain commented out.

site_name: BEHAVIOR-1K
repo_name: StanfordVL/BEHAVIOR-1K
site_url: https://behavior.stanford.edu/omnigibson # TODO: move this to root
repo_url: https://github.com/StanfordVL/BEHAVIOR-1K
theme: 
  name: material
  logo: assets/behavior_logo3.png
  favicon: assets/behavior_logo3.png
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.code.copy

  extra:
    homepage: https://behavior.stanford.edu

  custom_dir: docs/overrides

  # color info
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - assets/fold_api_reference.js

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: OmniGibson/omnigibson
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

# extra plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [OmniGibson/omnigibson]
          options:
            docstring_options:
              returns_named_value: false
  # - social
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - offline

nav:
  - Home: index.md
  - 2025 BEHAVIOR Challenge: challenge/overview.md
  - Documentation:
    - Installation: getting_started/installation.md
    - Important Concepts: getting_started/important_concepts.md
    - Components:
      - BDDL Tasks: behavior_components/behavior_tasks.md
      - Knowledgebase: behavior_components/behavior_knowledgebase.md
      - 3D Assets: behavior_components/3d_assets.md
      - JoyLo: behavior_components/joylo.md
    - OmniGibson:
      - Overview: omnigibson/overview.md
      - Quickstart: getting_started/quickstart.md
      - Examples: getting_started/examples.md
      - Prims: omnigibson/prims.md
      - Objects: omnigibson/objects.md
      - Object States: omnigibson/object_states.md
      - Robots: omnigibson/robots.md
      - Controllers: omnigibson/controllers.md
      - Sensors: omnigibson/sensors.md
      - Systems: omnigibson/systems.md
      - Scenes: omnigibson/scenes.md
      - Transition Rules: omnigibson/transition_rules.md
      - Simulator: omnigibson/simulator.md
      - Tasks: omnigibson/tasks.md
      - Environments: omnigibson/environments.md
      - Vector Environments: omnigibson/vector_environments.md
      - Setting Macros: omnigibson/setting_macros.md
      - Under the Hood - Isaac Sim: omnigibson/under_the_hood.md
    - Tutorials:
      - Demo Collection: tutorials/demo_collection.md
      - Running on a Compute Cluster: tutorials/running_on_a_compute_cluster.md
      - Remote Streaming: tutorials/remote_streaming.md    
      - Saving and Loading Simulation State: tutorials/save_load.md
      - Customizing Robots: tutorials/customizing_robots.md
      - Custom Robot Import: tutorials/custom_robot_import.md
      - Speed Optimization: community/speed_optimization.md
    - Roadmap: community/roadmap.md
    - FAQ: community/faq.md
    - Known Issues & Troubleshooting: community/known_issues.md
    - Contributing: community/contributing.md
    - API Reference: reference/*
    - Changelog: https://github.com/StanfordVL/OmniGibson/releases
  - Community: community/contact.md
  - Related Research: community/related_research.md
  - Workshops: community/workshops.md
  - BEHAVIOR-100:
    - Overview: behavior_100/overview.md
    - VR Dataset: behavior_100/dataset.md
    - Demo Gallery: behavior_100/demo_gallery.md

extra:
  analytics:
    provider: google
    property: G-6L1G6GMR63
  generator: false
  social:
    - icon: material/web
      link: https://svl.stanford.edu/
      name: SVL

copyright: © 2025 Stanford Vision and Learning Lab