combined:
- objects/batch-00
- objects/batch-01
- objects/batch-02
- objects/batch-03
- objects/batch-04
- objects/batch-05
- objects/batch-06
- objects/batch-07
- objects/batch-08
- objects/batch-09
- objects/batch-10
- objects/batch-11
- objects/batch-12
- objects/batch-13
- objects/custom-aa
- objects/legacy_batch-00
- objects/legacy_batch-01
- objects/legacy_batch-02
- objects/legacy_batch-03
- objects/legacy_batch-04
- objects/legacy_batch-05
- objects/legacy_batch-06
- objects/legacy_batch-07
- objects/legacy_batch-08
- objects/legacy_batch-09
- objects/legacy_batch-10
- objects/legacy_batch-11
- objects/legacy_batch-12
- objects/ping_pong-ab
- objects/procedural-aa
- objects/school_objects-aa
- objects/substances-01
- objects/task_relavant-ab
- objects/task_relevant-xy
- scenes/Beechwood_0_garden
- scenes/Beechwood_0_int
- scenes/Beechwood_1_int
- scenes/Benevolence_0_int
- scenes/Benevolence_1_int
- scenes/Benevolence_2_int
- scenes/Ihlen_0_int
- scenes/Ihlen_1_int
- scenes/Merom_0_garden
- scenes/Merom_0_int
- scenes/Merom_1_int
- scenes/Pomaria_0_garden
- scenes/Pomaria_0_int
- scenes/Pomaria_1_int
- scenes/Pomaria_2_int
- scenes/Rs_garden
- scenes/Rs_int
- scenes/Wainscott_0_garden
- scenes/Wainscott_0_int
- scenes/Wainscott_1_int
- scenes/commercial_kitchen_fire_extinguisher
- scenes/commercial_kitchen_pans
- scenes/gates_bedroom
- scenes/grocery_store_asian
- scenes/grocery_store_cafe
- scenes/grocery_store_convenience
- scenes/grocery_store_half_stocked
- scenes/hall_arch_wood
- scenes/hall_conference_large
- scenes/hall_glass_ceiling
- scenes/hall_train_station
- scenes/hotel_gym_spa
- scenes/hotel_suite_large
- scenes/hotel_suite_small
- scenes/house_double_floor_lower
- scenes/house_double_floor_upper
- scenes/house_single_floor
- scenes/office_bike
- scenes/office_cubicles_left
- scenes/office_cubicles_right
- scenes/office_large
- scenes/office_vendor_machine
- scenes/public_restroom_blue
- scenes/public_restroom_brown
- scenes/public_restroom_futuristic
- scenes/public_restroom_marble
- scenes/public_restroom_white
- scenes/restaurant_asian
- scenes/restaurant_brunch
- scenes/restaurant_cafeteria
- scenes/restaurant_diner
- scenes/restaurant_hotel
- scenes/restaurant_urban
- scenes/school_biology
- scenes/school_chemistry
- scenes/school_computer_lab_and_infirmary
- scenes/school_geography
- scenes/school_gym
final_scenes:
- scenes/Beechwood_0_garden
- scenes/Beechwood_0_int
- scenes/Beechwood_1_int
- scenes/Benevolence_0_int
- scenes/Benevolence_1_int
- scenes/Benevolence_2_int
- scenes/Ihlen_0_int
- scenes/Ihlen_1_int
- scenes/Merom_0_garden
- scenes/Merom_0_int
- scenes/Merom_1_int
- scenes/Pomaria_0_garden
- scenes/Pomaria_0_int
- scenes/Pomaria_1_int
- scenes/Pomaria_2_int
- scenes/Rs_garden
- scenes/Rs_int
- scenes/Wainscott_0_garden
- scenes/Wainscott_0_int
- scenes/Wainscott_1_int
- scenes/gates_bedroom
- scenes/grocery_store_asian
- scenes/grocery_store_cafe
- scenes/grocery_store_convenience
- scenes/grocery_store_half_stocked
- scenes/hall_arch_wood
- scenes/hall_conference_large
- scenes/hall_glass_ceiling
- scenes/hall_train_station
- scenes/hotel_gym_spa
- scenes/hotel_suite_large
- scenes/hotel_suite_small
- scenes/house_double_floor_lower
- scenes/house_double_floor_upper
- scenes/house_single_floor
- scenes/office_bike
- scenes/office_cubicles_left
- scenes/office_cubicles_right
- scenes/office_large
- scenes/office_vendor_machine
- scenes/restaurant_asian
- scenes/restaurant_brunch
- scenes/restaurant_cafeteria
- scenes/restaurant_diner
- scenes/restaurant_hotel
- scenes/restaurant_urban
- scenes/school_biology
- scenes/school_chemistry
- scenes/school_computer_lab_and_infirmary
- scenes/school_geography
- scenes/school_gym
objects:
- objects/batch-00
- objects/batch-01
- objects/batch-02
- objects/batch-03
- objects/batch-04
- objects/batch-05
- objects/batch-06
- objects/batch-07
- objects/batch-08
- objects/batch-09
- objects/batch-10
- objects/batch-11
- objects/batch-12
- objects/batch-13
- objects/custom-aa
- objects/legacy_batch-00
- objects/legacy_batch-01
- objects/legacy_batch-02
- objects/legacy_batch-03
- objects/legacy_batch-04
- objects/legacy_batch-05
- objects/legacy_batch-06
- objects/legacy_batch-07
- objects/legacy_batch-08
- objects/legacy_batch-09
- objects/legacy_batch-10
- objects/legacy_batch-11
- objects/legacy_batch-12
- objects/ping_pong-ab
- objects/procedural-aa
- objects/school_objects-aa
- objects/substances-01
- objects/task_relavant-ab
- objects/task_relevant-xy
scenes:
- scenes/Beechwood_0_garden
- scenes/Beechwood_0_int
- scenes/Beechwood_1_int
- scenes/Benevolence_0_int
- scenes/Benevolence_1_int
- scenes/Benevolence_2_int
- scenes/Ihlen_0_int
- scenes/Ihlen_1_int
- scenes/Merom_0_garden
- scenes/Merom_0_int
- scenes/Merom_1_int
- scenes/Pomaria_0_garden
- scenes/Pomaria_0_int
- scenes/Pomaria_1_int
- scenes/Pomaria_2_int
- scenes/Rs_garden
- scenes/Rs_int
- scenes/Wainscott_0_garden
- scenes/Wainscott_0_int
- scenes/Wainscott_1_int
- scenes/commercial_kitchen_fire_extinguisher
- scenes/commercial_kitchen_pans
- scenes/gates_bedroom
- scenes/grocery_store_asian
- scenes/grocery_store_cafe
- scenes/grocery_store_convenience
- scenes/grocery_store_half_stocked
- scenes/hall_arch_wood
- scenes/hall_conference_large
- scenes/hall_glass_ceiling
- scenes/hall_train_station
- scenes/hotel_gym_spa
- scenes/hotel_suite_large
- scenes/hotel_suite_small
- scenes/house_double_floor_lower
- scenes/house_double_floor_upper
- scenes/house_single_floor
- scenes/office_bike
- scenes/office_cubicles_left
- scenes/office_cubicles_right
- scenes/office_large
- scenes/office_vendor_machine
- scenes/public_restroom_blue
- scenes/public_restroom_brown
- scenes/public_restroom_futuristic
- scenes/public_restroom_marble
- scenes/public_restroom_white
- scenes/restaurant_asian
- scenes/restaurant_brunch
- scenes/restaurant_cafeteria
- scenes/restaurant_diner
- scenes/restaurant_hotel
- scenes/restaurant_urban
- scenes/school_biology
- scenes/school_chemistry
- scenes/school_computer_lab_and_infirmary
- scenes/school_geography
- scenes/school_gym
verified_scenes:
- scenes/Beechwood_0_garden
- scenes/Beechwood_0_int
- scenes/Beechwood_1_int
- scenes/Benevolence_0_int
- scenes/Benevolence_1_int
- scenes/Benevolence_2_int
- scenes/Ihlen_0_int
- scenes/Ihlen_1_int
- scenes/Merom_0_garden
- scenes/Merom_0_int
- scenes/Merom_1_int
- scenes/Pomaria_0_garden
- scenes/Pomaria_0_int
- scenes/Pomaria_1_int
- scenes/Pomaria_2_int
- scenes/Rs_garden
- scenes/Rs_int
- scenes/Wainscott_0_garden
- scenes/Wainscott_0_int
- scenes/Wainscott_1_int
- scenes/commercial_kitchen_fire_extinguisher
- scenes/commercial_kitchen_pans
- scenes/gates_bedroom
- scenes/grocery_store_asian
- scenes/grocery_store_cafe
- scenes/grocery_store_convenience
- scenes/grocery_store_half_stocked
- scenes/hall_arch_wood
- scenes/hall_conference_large
- scenes/hall_glass_ceiling
- scenes/hall_train_station
- scenes/hotel_gym_spa
- scenes/hotel_suite_large
- scenes/hotel_suite_small
- scenes/house_double_floor_lower
- scenes/house_double_floor_upper
- scenes/house_single_floor
- scenes/office_bike
- scenes/office_cubicles_left
- scenes/office_cubicles_right
- scenes/office_large
- scenes/office_vendor_machine
- scenes/public_restroom_blue
- scenes/public_restroom_brown
- scenes/public_restroom_futuristic
- scenes/public_restroom_marble
- scenes/public_restroom_white
- scenes/restaurant_asian
- scenes/restaurant_brunch
- scenes/restaurant_cafeteria
- scenes/restaurant_diner
- scenes/restaurant_hotel
- scenes/restaurant_urban
- scenes/school_biology
- scenes/school_chemistry
- scenes/school_computer_lab_and_infirmary
- scenes/school_geography
- scenes/school_gym
