env:
  device: null
  automatic_reset: false
  flatten_action_space: false
  flatten_obs_space: false
  use_external_obs: false
  initial_pos_z_offset: 0.1
  external_sensors: null

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  trav_map_resolution: 0.1
  default_erosion_radius: 0.0
  trav_map_with_objects: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: OG
  include_robots: true

robots:
  # - name: turtlebot1
  #   type: Turtlebot
  #   obs_modalities: [rgb]
  #   scale: 1.0
  #   self_collision: false
  #   action_normalize: true
  #   action_type: continuous
  #   initial_pos: [0.0, 0.0, 0.0]
  #   initial_quat: [0.0, 0.0, 0.0, 1.0]
  #   sensor_config:
  #     VisionSensor:
  #       sensor_kwargs:
  #         image_height: 128
  #         image_width: 128
  #     # ScanSensor:
  #     #   sensor_kwargs:
  #     #     min_range: 0.05
  #     #     max_range: 10.0
  #   controller_config:
  #     base:
  #       name: DifferentialDriveController

  - name: Locobot1
    type: Locobot
    obs_modalities: [rgb]
    scale: 1.0
    self_collision: false
    action_normalize: true
    action_type: continuous
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    # initial_pos: [0.0, 0.0, 0.0]
    # initial_quat: [0.0, 0.0, 0.0, 1.0]
    sensor_config:
      VisionSensor:
        sensor_kwargs:
          image_height: 128
          image_width: 128
      # ScanSensor:
      #   sensor_kwargs:
      #     min_range: 0.05
      #     max_range: 10.0
    controller_config:
      base:
        name: DifferentialDriveController

  # - name: Fetch1
  #   type: Fetch
  #   position: [0, 0, 0]
  #   orientation: [0, 0, 0, 1]
  #   obs_modalities: [scan, rgb, depth]
  #   scale: 1.0
  #   self_collision: false
  #   action_normalize: true
  #   action_type: continuous
  #   grasping_mode: physical
  #   rigid_trunk: false
  #   default_trunk_offset: 0.365
  #   default_arm_pose: diagonal30
  #   reset_joint_pos: tuck
  #   sensor_config:
  #     VisionSensor:
  #       sensor_kwargs:
  #         image_height: 128
  #         image_width: 128
  #     ScanSensor:
  #       sensor_kwargs:
  #         min_range: 0.05
  #         max_range: 10.0
  #   controller_config:
  #     base:
  #       name: DifferentialDriveController
  #     arm_0:
  #       name: InverseKinematicsController
  #       kv: 2.0
  #     gripper_0:
  #       name: MultiFingerGripperController
  #       mode: binary
  #     camera:
  #       name: JointController
  #       use_delta_commands: False

  # - name: turtlebot2
  #   type: Turtlebot
  #   obs_modalities: [scan, rgb, depth]
  #   scale: 1.0
  #   self_collision: false
  #   action_normalize: true
  #   action_type: continuous
  #   initial_pos: [2.0, 0.0, 0.0]
  #   initial_quat: [0.0, 0.0, 0.0, 1.0]
  #   sensor_config:
  #     VisionSensor:
  #       sensor_kwargs:
  #         image_height: 128
  #         image_width: 128
  #     ScanSensor:
  #       sensor_kwargs:
  #         min_range: 0.05
  #         max_range: 10.0
  #   controller_config:
  #     base:
  #       name: DifferentialDriveController

  # - name: turtlebot3
  #   type: Turtlebot
  #   obs_modalities: [scan, rgb, depth]
  #   scale: 1.0
  #   self_collision: false
  #   action_normalize: true
  #   action_type: continuous
  #   initial_pos: [2.0, 2.0, 0.0]
  #   initial_quat: [0.0, 0.0, 0.0, 1.0]
  #   sensor_config:
  #     VisionSensor:
  #       sensor_kwargs:
  #         image_height: 128
  #         image_width: 128
  #     ScanSensor:
  #       sensor_kwargs:
  #         min_range: 0.05
  #         max_range: 10.0
  #   controller_config:
  #     base:
  #       name: DifferentialDriveController

objects: []

task:
  type: PointNavigationTask
  robot_idn: 0
  floor: 0
  initial_pos: null
  initial_quat: null
  goal_pos: null
  goal_tolerance: 0.36
  goal_in_polar: false
  path_range: [1.0, 10.0]
  visualize_goal: true
  visualize_path: false
  n_vis_waypoints: 25
  reward_type: geodesic
  termination_config:
    max_collisions: 500
    max_steps: 500
    fall_height: 0.03
  reward_config:
    r_potential: 1.0
    r_collision: 0.1
    r_pointgoal: 10.0
