"""
Script to import objects generated by process_vid2room.py into OmniGibson-compatible USD format.
Uses pre-computed decimated meshes and collision hulls from vid2scene_step9_preprocess_meshes.py.
"""

import argparse
import hashlib
import pathlib
import traceback
import shutil
import tempfile
import os
import io
import json
import math
from tqdm import tqdm
from xml.dom import minidom
import xml.etree.ElementTree as ET
import random

import numpy as np
import trimesh
import torch as th

import omnigibson as og
from omnigibson.macros import gm
from omnigibson.utils.asset_conversion_utils import (
    import_og_asset_from_urdf,
)

gm.HEADLESS = True

RESTART_EVERY = 64

# Structure categories to skip (handled separately)
SKIP_CATEGORIES = {
    "wall",
    "floor",
    "ceiling",
    "window",
    "door",
    "doorway",
    "stairs",
    # not structure but still annoying
    "curtain",
    "pillow",
}


def load_collision_meshes_from_npz(npz_path: pathlib.Path) -> list:
    """
    Load pre-computed collision meshes from an NPZ file.

    Args:
        npz_path: Path to the NPZ file containing collision mesh data

    Returns:
        List of trimesh.Trimesh collision meshes
    """
    data = np.load(npz_path)
    collision_meshes = []
    i = 0
    while f"vertices_{i}" in data:
        vertices = data[f"vertices_{i}"]
        faces = data[f"faces_{i}"]
        mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
        collision_meshes.append(mesh)
        i += 1
    return collision_meshes


def generate_urdf_with_precomputed_collision(
    asset_path,
    out_dir,
    category,
    mdl,
    collision_meshes,
    up_axis="z",
    scale=1.0,
    overwrite=False,
):
    """
    Generate URDF file using pre-computed collision meshes.

    Args:
        asset_path (str or Path): Path to the input mesh file (.obj, .glb, .gltf)
        out_dir (str or Path): Output directory
        category (str): Category name for the object
        mdl (str): Model name
        collision_meshes (list of trimesh.Trimesh): Pre-computed collision meshes
        up_axis (str): Up axis for the model ("y" or "z")
        scale (float): Scale factor for the mesh
        overwrite (bool): Whether to overwrite existing files

    Returns:
        str: Path to the generated URDF file
    """
    # Convert to Path objects
    if isinstance(out_dir, str):
        out_dir = pathlib.Path(out_dir)
    if isinstance(asset_path, str):
        asset_path = pathlib.Path(asset_path)

    # Validate that the filename starts with a letter. Isaac 4.5 has issues if you don't do this.
    assert asset_path.stem[
        0
    ].isalpha(), f"Invalid asset path: {asset_path}. Isaac Sim expects the filename to start with a letter."

    # Create directory structure
    if not overwrite:
        assert not out_dir.exists(), f"Object directory {out_dir} already exists!"
    out_dir.mkdir(parents=True, exist_ok=True)

    obj_name = "_".join([category, mdl])

    # Keep track of the base transform
    rpy = [0, 0, 0]
    if up_axis == "y":
        rpy = [math.pi / 2, 0, 0]

    # Create directory structure for the output
    obj_link_mesh_folder = out_dir / "shape"
    obj_link_mesh_folder.mkdir(exist_ok=True)
    obj_link_collision_mesh_folder = obj_link_mesh_folder / "collision"
    obj_link_collision_mesh_folder.mkdir(exist_ok=True)

    # Process collision meshes
    collision_info = []
    for i, collision_mesh in enumerate(collision_meshes):
        # Export collision mesh filename
        collision_filename = f"{obj_name}_base_link_collision_{i}.obj"

        # Scale collision mesh to unit bbox if needed
        bounding_box = collision_mesh.bounding_box.extents
        assert all(x > 0 for x in bounding_box), f"Invalid bounding box: {bounding_box}"

        collision_scale = 1.0 / bounding_box
        collision_scale_matrix = th.eye(4)
        collision_scale_matrix[:3, :3] = th.diag(th.as_tensor(collision_scale))

        # Create a copy to avoid modifying the original
        scaled_collision_mesh = collision_mesh.copy()
        scaled_collision_mesh.apply_transform(collision_scale_matrix.numpy())

        # Export collision mesh
        collision_path = obj_link_collision_mesh_folder / collision_filename
        scaled_collision_mesh.export(collision_path, file_type="obj")

        # Since we've already applied the transform, scale includes only the sizing adjustment
        collision_info.append({"filename": collision_path, "scale": 1.0 / collision_scale})

    # Generate URDF XML
    tree_root = ET.Element("robot")
    tree_root.attrib = {"name": mdl}

    # Create a base_link as the root
    base_link = ET.SubElement(tree_root, "link")
    base_link.attrib = {"name": "base_link"}

    rpy_str = " ".join(str(item) for item in rpy)

    # Add visual geometry
    visual_xml = ET.SubElement(base_link, "visual")
    visual_origin_xml = ET.SubElement(visual_xml, "origin")

    visual_geometry_xml = ET.SubElement(visual_xml, "geometry")
    visual_mesh_xml = ET.SubElement(visual_geometry_xml, "mesh")
    visual_mesh_xml.attrib = {
        "filename": str(asset_path),
        "scale": f"{scale} {scale} {scale}",
    }

    # Add collision geometries
    for i, collision in enumerate(collision_info):
        collision_xml = ET.SubElement(base_link, "collision")
        collision_xml.attrib = {"name": f"base_link_collision_{i}"}
        collision_origin_xml = ET.SubElement(collision_xml, "origin")
        collision_origin_xml.attrib = {"xyz": "0 0 0", "rpy": rpy_str}
        collision_geometry_xml = ET.SubElement(collision_xml, "geometry")
        collision_mesh_xml = ET.SubElement(collision_geometry_xml, "mesh")
        collision_mesh_xml.attrib = {
            "filename": str(collision["filename"]),
            "scale": " ".join(str(item) for item in scale * collision["scale"]),
        }

    # Save URDF file
    xmlstr = minidom.parseString(ET.tostring(tree_root)).toprettyxml(indent="   ")
    xmlio = io.StringIO(xmlstr)
    tree = ET.parse(xmlio)

    urdf_dir = out_dir / "urdf"
    urdf_dir.mkdir(exist_ok=True)
    urdf_path = urdf_dir / f"{mdl}.urdf"
    with open(urdf_path, "wb") as f:
        tree.write(f, xml_declaration=True)

    return str(urdf_path)


def import_vid2room_object(
    decimated_path: pathlib.Path,
    collision_path: pathlib.Path,
    category: str,
    model: str,
    dataset_name: str,
):
    """
    Imports a vid2room object asset into an OmniGibson-compatible USD format.
    Uses pre-computed decimated mesh and collision hulls.

    Args:
        decimated_path: Path to the decimated GLB file
        collision_path: Path to the collision NPZ file
        category: Object category
        model: Model name
        dataset_name: Name of the dataset (e.g., "vid2room")
    """
    dataset_root = pathlib.Path(gm.DATA_PATH) / dataset_name
    model_root = dataset_root / "objects" / category / model
    success_file = model_root / "import.success"

    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            # Copy the decimated mesh to temp dir with a valid filename
            # (must start with a letter for Isaac Sim)
            asset_path = os.path.join(temp_dir, f"vid2room_{model}.glb")
            shutil.copy(decimated_path, asset_path)

            # Load pre-computed collision meshes
            collision_meshes = load_collision_meshes_from_npz(collision_path)

            # Generate URDF with pre-computed collision meshes
            urdf_path = generate_urdf_with_precomputed_collision(
                asset_path,
                temp_dir,
                category,
                model,
                collision_meshes,
                overwrite=True,
            )
            assert urdf_path is not None, f"Failed to generate URDF for {asset_path}"

            # Convert to USD
            import_og_asset_from_urdf(
                category=category,
                model=model,
                urdf_path=str(urdf_path),
                collision_method=None,
                dataset_name=dataset_name,
                hull_count=32,
                overwrite=False,
                use_usda=False,
            )

            # Touch a success file.
            success_file.touch()
    finally:
        if og.sim:
            og.clear()


def find_vid2room_objects(vid2room_root: pathlib.Path):
    """
    Find all pre-processed vid2room objects (decimated mesh + collision hulls).

    Args:
        vid2room_root: Root directory containing vid2room outputs

    Returns:
        List of tuples: (decimated_path, collision_path, room_path, segment_name)
    """
    objects = []

    # Load the interesting scenes dict
    with open("/home/cgokmen/projects/BEHAVIOR-1K/slurm/interesting_scenes.json", "r") as f:
        interesting_scenes = [pathlib.Path(k) for k in json.load(f)]

    # Find all room directories with pre-processed mesh outputs
    for interesting_scene_root in interesting_scenes:
        decimated_dir = interesting_scene_root / "obj_meshes_v9_pointmap_decimated"
        collision_dir = interesting_scene_root / "obj_meshes_v9_pointmap_collision"

        for collision_path in collision_dir.glob("*.npz"):
            segment_name = collision_path.stem
            decimated_path = decimated_dir / f"{segment_name}.glb"

            # Skip structure categories
            base_category = segment_name.rsplit("-", 2)[0]
            if base_category in SKIP_CATEGORIES:
                continue

            objects.append((decimated_path, collision_path, interesting_scene_root, segment_name))

    return objects


def main():
    parser = argparse.ArgumentParser(description="Import vid2room objects into OmniGibson USD format")
    parser.add_argument("task_id", type=int, help="Task ID (0-indexed)")
    parser.add_argument("total_tasks", type=int, help="Total number of tasks")
    parser.add_argument("--vid2room-root", type=str, required=True, help="Root directory of vid2room outputs")
    parser.add_argument("--dataset-name", type=str, default="vid2room", help="Dataset name (defaults to 'vid2room')")
    parser.add_argument("--success-prefix", default="", help="Prefix for success files")
    parser.add_argument(
        "--restart-every", type=int, default=RESTART_EVERY, help="Restart after processing this many objects"
    )
    parser.add_argument("--limit", type=int, default=None, help="Limit number of objects to process (for testing)")
    args = parser.parse_args()

    # Setup paths
    vid2room_root = pathlib.Path(args.vid2room_root)
    dataset_name = args.dataset_name
    dataset_root = pathlib.Path(gm.DATA_PATH) / dataset_name
    dataset_root.mkdir(exist_ok=True, parents=True)

    errors_dir = dataset_root / "errors"
    errors_dir.mkdir(exist_ok=True)
    jobs_dir = dataset_root / "jobs"
    jobs_dir.mkdir(exist_ok=True)

    # Find all objects
    print(f"Finding pre-processed objects in {vid2room_root}...")
    objects = find_vid2room_objects(vid2room_root)
    print(f"Found {len(objects)} pre-processed objects")

    # Re-sort jobs differently per run with a fixed salt for consistency
    objects.sort(key=lambda x: hashlib.md5((str(x[0]) + "potato").encode()).hexdigest())

    rank = args.task_id
    world_size = args.total_tasks

    # Get objects for this task
    task_objects = objects[rank::world_size]
    if args.limit:
        task_objects = task_objects[: args.limit]

    print(f"Processing {len(task_objects)} objects in task {rank}/{world_size}")

    completed_count = 0
    for decimated_path, collision_path, room_path, segment_name in tqdm(task_objects):
        # Extract category from segment name (format: "category-segmentN-M")
        parts = segment_name.rsplit("-", 2)
        if len(parts) >= 1:
            category = parts[0]
        else:
            category = "object"

        # Sanitize category and model names
        category = "".join(c if c.isalnum() or c == "_" else "_" for c in category.lower())

        # Create unique model name including room info
        room_id = f"{room_path.parent.parent.name}_{room_path.name}"
        model = f"{room_id}_{segment_name}".replace("-", "_")
        model = "".join(c if c.isalnum() or c == "_" else "" for c in model.lower())

        model_root = dataset_root / "objects" / category / model
        success_file = model_root / "import.success"

        if model_root.exists():
            # Check if we're fully done
            if success_file.exists():
                continue
            # Otherwise nuke the directory
            shutil.rmtree(model_root)

        try:
            import_vid2room_object(
                decimated_path=decimated_path,
                collision_path=collision_path,
                category=category,
                model=model,
                dataset_name=dataset_name,
            )
            completed_count += 1
        except Exception as e:
            print(f"Error processing {decimated_path}: {e}")
            with open(errors_dir / f"{model}", "w") as f:
                f.write(
                    f"Decimated: {decimated_path}\nCollision: {collision_path}\nRoom: {room_path}\nSegment: {segment_name}\n\n"
                )
                f.write(traceback.format_exc())

        if args.restart_every and completed_count >= args.restart_every:
            return

    # If we reach here, we're done. Record the rank success.
    success_filename = f"{args.success_prefix}_{rank}.success" if args.success_prefix else f"{rank}.success"
    (jobs_dir / success_filename).touch()

    og.shutdown()


if __name__ == "__main__":
    main()
