"""
Script to import objects generated by process_vid2room.py into OmniGibson-compatible USD format.
Combines import logic from import_hssd_objects.py with decimation from mesh_placement.ipynb.
"""

import argparse
import hashlib
import pathlib
import traceback
import shutil
import tempfile
import os
import json
from tqdm import tqdm

import numpy as np
import trimesh

import omnigibson as og
from omnigibson.macros import gm
from omnigibson.utils.asset_conversion_utils import (
    import_og_asset_from_urdf,
    generate_urdf_for_mesh,
)

gm.HEADLESS = True

RESTART_EVERY = 64

# Structure categories to skip (handled separately)
SKIP_CATEGORIES = {
    "wall",
    "floor",
    "ceiling",
    "window",
    "door",
    "doorway",
    "stairs",
    # not structure but still annoying
    "curtain",
    "pillow",
}


def decimate_mesh(mesh: trimesh.Trimesh, target_face_count: int = 10000, aggression: int = 2) -> trimesh.Trimesh:
    """
    Decimate a mesh to reduce face count while preserving vertex colors.
    
    Args:
        mesh: The trimesh object to decimate
        target_face_count: Target number of faces after decimation
        aggression: Aggression level for decimation (higher = more aggressive)
    
    Returns:
        Decimated trimesh object with interpolated vertex colors
    """
    if len(mesh.faces) <= target_face_count:
        return mesh
    
    # Simplify the mesh
    better_mesh = mesh.simplify_quadric_decimation(face_count=target_face_count, aggression=aggression)
    
    # Update the vertex colors if they exist
    if hasattr(mesh.visual, 'vertex_colors') and mesh.visual.vertex_colors is not None:
        try:
            from sklearn.neighbors import KNeighborsRegressor
            neigh = KNeighborsRegressor(n_neighbors=3)
            neigh.fit(mesh.vertices, np.array(mesh.visual.vertex_colors, dtype=float))
            better_mesh.visual.vertex_colors = neigh.predict(better_mesh.vertices).astype(np.uint8)
        except Exception as e:
            print(f"Warning: Could not interpolate vertex colors during decimation: {e}")
    
    return better_mesh


def import_vid2room_object(
    orig_path: pathlib.Path,
    category: str,
    model: str,
    dataset_name: str,
    decimate: bool = True,
    target_face_count: int = 10000,
):
    """
    Imports a vid2room object asset into an OmniGibson-compatible USD format.
    
    Args:
        orig_path: Path to the GLB file
        category: Object category
        model: Model name
        dataset_name: Name of the dataset (e.g., "vid2room")
        decimate: Whether to decimate the mesh
        target_face_count: Target face count for decimation
    """
    dataset_root = pathlib.Path(gm.DATA_PATH) / dataset_name
    model_root = dataset_root / "objects" / category / model
    success_file = model_root / "import.success"

    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            # Load the mesh
            mesh = trimesh.load(orig_path, force="mesh")
            
            # Decimate if requested
            if decimate and len(mesh.faces) > target_face_count:
                print(f"Decimating mesh from {len(mesh.faces)} to {target_face_count} faces")
                mesh = decimate_mesh(mesh, target_face_count=target_face_count)
            
            # Export the (possibly decimated) mesh as GLB
            asset_path = os.path.join(temp_dir, f"vid2room_{model}.glb")
            mesh.export(asset_path)

            # Try to generate URDF, may raise ValueError if too many submeshes
            urdf_path = generate_urdf_for_mesh(
                asset_path,
                temp_dir,
                category,
                model,
                collision_method="coacd",
                hull_count=32,
                check_scale=False,
                rescale=False,
                overwrite=True,
            )
            assert urdf_path is not None, f"Failed to generate URDF for {asset_path}"

            # Convert to USD
            import_og_asset_from_urdf(
                category=category,
                model=model,
                urdf_path=str(urdf_path),
                collision_method=None,
                dataset_name=dataset_name,
                hull_count=32,
                overwrite=False,
                use_usda=False,
            )

            # Touch a success file.
            success_file.touch()
    finally:
        if og.sim:
            og.clear()


def find_vid2room_objects(vid2room_root: pathlib.Path, mesh_subdir: str = "obj_meshes_v9_pointmap"):
    """
    Find all GLB objects generated by process_vid2room.py.
    
    Args:
        vid2room_root: Root directory containing vid2room outputs
        mesh_subdir: Subdirectory containing the meshes
    
    Returns:
        List of tuples: (glb_path, room_path, segment_name)
    """
    objects = []

    # Load the interesting scenes dict
    with open("/home/cgokmen/projects/BEHAVIOR-1K/slurm/interesting_scenes.json", "r") as f:
        interesting_scenes = {pathlib.Path(k) for k in json.load(f)}

    # Find all room directories with mesh outputs
    for interesting_scene_root in interesting_scenes:
        mesh_dir = interesting_scene_root / mesh_subdir
        for json_path in mesh_dir.glob("*.json"):
            glb_path = json_path.with_suffix(".glb")
            
            segment_name = glb_path.stem
            
            # Skip structure categories
            base_category = segment_name.rsplit("-", 2)[0]
            if base_category in SKIP_CATEGORIES:
                continue
            
            objects.append((glb_path, room_path, segment_name))
    
    return objects


def main():
    parser = argparse.ArgumentParser(description="Import vid2room objects into OmniGibson USD format")
    parser.add_argument("task_id", type=int, help="Task ID (0-indexed)")
    parser.add_argument("total_tasks", type=int, help="Total number of tasks")
    parser.add_argument("--vid2room-root", type=str, required=True, help="Root directory of vid2room outputs")
    parser.add_argument("--dataset-name", type=str, default="vid2room",
                        help="Dataset name (defaults to 'vid2room')")
    parser.add_argument("--mesh-subdir", type=str, default="obj_meshes_v9_pointmap",
                        help="Subdirectory containing the meshes")
    parser.add_argument("--success-prefix", default="", help="Prefix for success files")
    parser.add_argument("--restart-every", type=int, default=RESTART_EVERY,
                        help="Restart after processing this many objects")
    parser.add_argument("--no-decimate", action="store_true", help="Disable mesh decimation")
    parser.add_argument("--target-face-count", type=int, default=10000,
                        help="Target face count for decimation")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of objects to process (for testing)")
    args = parser.parse_args()

    # Setup paths
    vid2room_root = pathlib.Path(args.vid2room_root)
    dataset_name = args.dataset_name
    dataset_root = pathlib.Path(gm.DATA_PATH) / dataset_name
    dataset_root.mkdir(exist_ok=True, parents=True)
    
    errors_dir = dataset_root / "errors"
    errors_dir.mkdir(exist_ok=True)
    jobs_dir = dataset_root / "jobs"
    jobs_dir.mkdir(exist_ok=True)

    # Find all objects
    print(f"Finding objects in {vid2room_root}...")
    objects = find_vid2room_objects(vid2room_root, args.mesh_subdir)
    print(f"Found {len(objects)} objects")

    # Re-sort jobs differently per run with a fixed salt for consistency
    objects.sort(
        key=lambda x: hashlib.md5(
            (str(x[0]) + "potato").encode()
        ).hexdigest()
    )

    rank = args.task_id
    world_size = args.total_tasks

    # Get objects for this task
    task_objects = objects[rank::world_size]
    if args.limit:
        task_objects = task_objects[:args.limit]

    print(f"Processing {len(task_objects)} objects in task {rank}/{world_size}")

    completed_count = 0
    for glb_path, room_path, segment_name in tqdm(task_objects):
        # Extract category from segment name (format: "category-segmentN-M")
        parts = segment_name.rsplit("-", 2)
        if len(parts) >= 1:
            category = parts[0]
        else:
            category = "object"
        
        # Sanitize category and model names
        category = "".join(c if c.isalnum() or c == "_" else "_" for c in category.lower())
        
        # Create unique model name including room info
        room_id = f"{room_path.parent.parent.name}_{room_path.name}"
        model = f"{room_id}_{segment_name}".replace("-", "_")
        model = "".join(c if c.isalnum() or c == "_" else "" for c in model.lower())

        model_root = dataset_root / "objects" / category / model
        success_file = model_root / "import.success"

        if model_root.exists():
            # Check if we're fully done
            if success_file.exists():
                continue
            # Otherwise nuke the directory
            shutil.rmtree(model_root)

        try:
            import_vid2room_object(
                orig_path=glb_path,
                category=category,
                model=model,
                dataset_name=dataset_name,
                decimate=not args.no_decimate,
                target_face_count=args.target_face_count,
            )
            completed_count += 1
        except Exception as e:
            print(f"Error processing {glb_path}: {e}")
            with open(errors_dir / f"{model}", "w") as f:
                f.write(f"GLB: {glb_path}\nRoom: {room_path}\nSegment: {segment_name}\n\n")
                f.write(traceback.format_exc())

        if args.restart_every and completed_count >= args.restart_every:
            return

    # If we reach here, we're done. Record the rank success.
    success_filename = f"{args.success_prefix}_{rank}.success" if args.success_prefix else f"{rank}.success"
    (jobs_dir / success_filename).touch()

    og.shutdown()


if __name__ == "__main__":
    main()

